using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anela.Heblo.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddStockTakingRecord : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "dbo");

            // Try to create table, if it exists just modify the Date column type
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS dbo.""StockTakingResults"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Type"" integer NOT NULL,
                    ""Code"" text NOT NULL,
                    ""AmountNew"" double precision NOT NULL,
                    ""AmountOld"" double precision NOT NULL,
                    ""Date"" timestamp NOT NULL,
                    ""User"" text,
                    ""Error"" text,
                    CONSTRAINT ""PK_StockTakingResults"" PRIMARY KEY (""Id"")
                );
            ");

            // Change Date column type if it exists with wrong type
            migrationBuilder.Sql(@"
                ALTER TABLE dbo.""StockTakingResults"" 
                ALTER COLUMN ""Date"" TYPE timestamp;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "StockTakingResults",
                schema: "dbo");
        }
    }
}
