// <auto-generated />
using System;
using Anela.Heblo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anela.Heblo.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120182412_RemoveVerifiedStateFromStockUpOperations")]
    partial class RemoveVerifiedStateFromStockUpOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anela.Heblo.Domain.Features.BackgroundJobs.RecurringJobConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_modified_by");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_recurring_job_configurations_is_enabled");

                    b.HasIndex("JobName")
                        .IsUnique()
                        .HasDatabaseName("IX_recurring_job_configurations_job_name");

                    b.ToTable("recurring_job_configurations", (string)null);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Bank.BankStatementImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Account");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("Currency");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ImportDate");

                    b.Property<string>("ImportResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ImportResult");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("ItemCount");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("StatementDate");

                    b.Property<string>("TransferId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TransferId");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .HasDatabaseName("IX_BankStatements_Account");

                    b.HasIndex("ImportDate")
                        .HasDatabaseName("IX_BankStatements_ImportDate");

                    b.HasIndex("StatementDate")
                        .HasDatabaseName("IX_BankStatements_StatementDate");

                    b.HasIndex("TransferId")
                        .IsUnique()
                        .HasDatabaseName("IX_BankStatements_TransferId");

                    b.ToTable("BankStatements", "dbo");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Catalog.ManufactureDifficultySetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DifficultyValue")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("IX_ManufactureDifficultySettings_ProductCode");

                    b.HasIndex("ProductCode", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_ManufactureDifficultySettings_ProductCode_Validity");

                    b.ToTable("ManufactureDifficultySettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManufactureDifficultySettings_ValidDates", "\"ValidFrom\" IS NULL OR \"ValidTo\" IS NULL OR \"ValidFrom\" < \"ValidTo\"");
                        });
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Catalog.Stock.StockTakingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountNew")
                        .HasColumnType("double precision");

                    b.Property<double>("AmountOld")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StockTakingResults", "dbo");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Catalog.Stock.StockUpOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_StockUpOperations_DocumentNumber_Unique");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_StockUpOperations_State");

                    b.HasIndex("SourceType", "SourceId")
                        .HasDatabaseName("IX_StockUpOperations_Source");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("IX_StockUpOperations_State_CreatedAt");

                    b.ToTable("StockUpOperations", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.InvoiceClassification.ClassificationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbraInvoiceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountingTemplateCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AccountingTemplateCode");

                    b.Property<Guid?>("ClassificationRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AbraInvoiceId")
                        .HasDatabaseName("IX_ClassificationHistory_AbraInvoiceId");

                    b.HasIndex("ClassificationRuleId");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_ClassificationHistory_CompanyName");

                    b.HasIndex("InvoiceNumber")
                        .HasDatabaseName("IX_ClassificationHistory_InvoiceNumber");

                    b.HasIndex("Result")
                        .HasDatabaseName("IX_ClassificationHistory_Result");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_ClassificationHistory_Timestamp");

                    b.ToTable("ClassificationHistory", (string)null);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.InvoiceClassification.ClassificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountingTemplateCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AccountingTemplateCode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RuleTypeIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.HasIndex("RuleTypeIdentifier", "Pattern")
                        .HasDatabaseName("IX_ClassificationRules_RuleTypeIdentifier_Pattern");

                    b.ToTable("ClassificationRules", (string)null);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Invoices.IssuedInvoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<int>("BillingMethod")
                        .HasColumnType("integer")
                        .HasColumnName("BillingMethod");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Currency");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text")
                        .HasColumnName("CustomerName");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DueDate");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("ErrorMessage");

                    b.Property<int?>("ErrorType")
                        .HasColumnType("integer")
                        .HasColumnName("ErrorType");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("InvoiceDate");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean")
                        .HasColumnName("IsSynced");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("integer")
                        .HasColumnName("ItemsCount");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastSyncTime");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("Price");

                    b.Property<decimal>("PriceC")
                        .HasColumnType("numeric")
                        .HasColumnName("PriceC");

                    b.Property<int>("ShippingMethod")
                        .HasColumnType("integer")
                        .HasColumnName("ShippingMethod");

                    b.Property<int>("SyncHistoryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("SyncHistoryCount");

                    b.Property<DateTime>("TaxDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("TaxDate");

                    b.Property<long?>("VarSymbol")
                        .HasColumnType("bigint")
                        .HasColumnName("VarSymbol");

                    b.Property<bool?>("VatPayer")
                        .HasColumnType("boolean")
                        .HasColumnName("VatPayer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("IX_IssuedInvoice_InvoiceDate");

                    b.HasIndex("LastSyncTime")
                        .HasDatabaseName("IX_IssuedInvoice_LastSyncTime");

                    b.ToTable("IssuedInvoice", "dbo");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Invoices.IssuedInvoiceSyncData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("Data");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("IsSuccess");

                    b.Property<string>("IssuedInvoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IssuedInvoiceId");

                    b.Property<DateTime>("SyncTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("SyncTime");

                    b.HasKey("Id");

                    b.HasIndex("IssuedInvoiceId");

                    b.ToTable("IssuedInvoiceSyncData", "dbo");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedByUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeletedByUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModifiedByUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_JournalEntries_CreatedByUserId");

                    b.HasIndex("EntryDate")
                        .HasDatabaseName("IX_JournalEntries_EntryDate");

                    b.HasIndex("IsDeleted", "EntryDate")
                        .HasDatabaseName("IX_JournalEntries_IsDeleted_EntryDate");

                    b.ToTable("JournalEntries", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntryProduct", b =>
                {
                    b.Property<int>("JournalEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCodePrefix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("JournalEntryId", "ProductCodePrefix");

                    b.HasIndex("ProductCodePrefix")
                        .HasDatabaseName("IX_JournalEntryProducts_ProductCode");

                    b.ToTable("JournalEntryProducts", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_JournalEntryTags_Name");

                    b.ToTable("JournalEntryTags", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntryTagAssignment", b =>
                {
                    b.Property<int>("JournalEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("JournalEntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("JournalEntryTagAssignments", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.GiftPackageManufacture.GiftPackageManufactureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufactureLogId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacture_log_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<int>("QuantityConsumed")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_consumed");

                    b.HasKey("Id");

                    b.HasIndex("ManufactureLogId")
                        .HasDatabaseName("ix_gift_package_manufacture_items_manufacture_log_id");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("ix_gift_package_manufacture_items_product_code");

                    b.ToTable("gift_package_manufacture_items", (string)null);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.GiftPackageManufacture.GiftPackageManufactureLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GiftPackageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gift_package_code");

                    b.Property<int>("QuantityCreated")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_created");

                    b.Property<bool>("StockOverrideApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("stock_override_applied");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_gift_package_manufacture_logs_created_at");

                    b.HasIndex("GiftPackageCode")
                        .HasDatabaseName("ix_gift_package_manufacture_logs_gift_package_code");

                    b.ToTable("gift_package_manufacture_logs", (string)null);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultReceiveState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastStateChanged")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastStateChanged");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransportBox", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBoxItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DateAdded");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TransportBoxId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAdded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransportBoxId");

                    b.ToTable("TransportBoxItem", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBoxStateLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("StateDate");

                    b.Property<int?>("TransportBoxId")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransportBoxId");

                    b.ToTable("TransportBoxStateLog", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("ErpDiscardResidueDocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ErpDiscardResidueDocumentNumberDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("ErpOrderNumberProduct")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ErpOrderNumberProductDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("ErpOrderNumberSemiproduct")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ErpOrderNumberSemiproductDate")
                        .HasColumnType("timestamp");

                    b.Property<bool>("ManualActionRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("ManufactureType")
                        .HasColumnType("integer");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StateChangedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("StateChangedByUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_ManufactureOrders_CreatedDate");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ManufactureOrders_OrderNumber");

                    b.HasIndex("ResponsiblePerson")
                        .HasDatabaseName("IX_ManufactureOrders_ResponsiblePerson");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_ManufactureOrders_State");

                    b.ToTable("ManufactureOrders", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrderNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedByUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ManufactureOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ManufactureOrderNotes_CreatedAt");

                    b.HasIndex("ManufactureOrderId")
                        .HasDatabaseName("IX_ManufactureOrderNotes_ManufactureOrderId");

                    b.ToTable("ManufactureOrderNotes", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualQuantity")
                        .IsRequired()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ManufactureOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SemiProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManufactureOrderId")
                        .HasDatabaseName("IX_ManufactureOrderProducts_ManufactureOrderId");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("IX_ManufactureOrderProducts_ProductCode");

                    b.HasIndex("SemiProductCode")
                        .HasDatabaseName("IX_ManufactureOrderProducts_SemiProductCode");

                    b.ToTable("ManufactureOrderProducts", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrderSemiProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualQuantity")
                        .IsRequired()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("BatchMultiplier")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("ExpirationMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12);

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ManufactureOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ManufactureOrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_ManufactureOrderSemiProducts_ManufactureOrderId");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("IX_ManufactureOrderSemiProducts_ProductCode");

                    b.ToTable("ManufactureOrderSemiProducts", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.PackingMaterials.PackingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumptionRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ConsumptionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_PackingMaterial_Name");

                    b.ToTable("PackingMaterial", "dbo");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.PackingMaterials.PackingMaterialLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LogType")
                        .HasColumnType("integer");

                    b.Property<decimal>("NewQuantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("OldQuantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("PackingMaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LogType")
                        .HasDatabaseName("IX_PackingMaterialLog_LogType");

                    b.HasIndex("PackingMaterialId")
                        .HasDatabaseName("IX_PackingMaterialLog_PackingMaterialId");

                    b.HasIndex("PackingMaterialId", "Date")
                        .HasDatabaseName("IX_PackingMaterialLog_MaterialId_Date");

                    b.ToTable("PackingMaterialLog", "dbo");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Purchase.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactVia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp");

                    b.Property<bool>("InvoiceAcquired")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("PurchaseOrders", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Purchase.PurchaseOrderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderHistory", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Purchase.PurchaseOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLines", "public");
                });

            modelBuilder.Entity("Anela.Heblo.Xcc.Domain.UserDashboardSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDashboardSettings", (string)null);
                });

            modelBuilder.Entity("Anela.Heblo.Xcc.Domain.UserDashboardTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp");

                    b.Property<string>("TileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DisplayOrder");

                    b.HasIndex("UserId", "TileId")
                        .IsUnique();

                    b.ToTable("UserDashboardTiles", (string)null);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.InvoiceClassification.ClassificationHistory", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.InvoiceClassification.ClassificationRule", "ClassificationRule")
                        .WithMany()
                        .HasForeignKey("ClassificationRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClassificationRule");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Invoices.IssuedInvoiceSyncData", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Invoices.IssuedInvoice", null)
                        .WithMany("SyncHistory")
                        .HasForeignKey("IssuedInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Anela.Heblo.Domain.Features.Invoices.IssuedInvoiceError", "Error", b1 =>
                        {
                            b1.Property<int>("IssuedInvoiceSyncDataId")
                                .HasColumnType("integer");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Error_Code");

                            b1.Property<int>("ErrorType")
                                .HasColumnType("integer")
                                .HasColumnName("Error_ErrorType");

                            b1.Property<string>("Field")
                                .HasColumnType("text")
                                .HasColumnName("Error_Field");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Error_Message");

                            b1.HasKey("IssuedInvoiceSyncDataId");

                            b1.ToTable("IssuedInvoiceSyncData", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("IssuedInvoiceSyncDataId");
                        });

                    b.Navigation("Error");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntryProduct", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Journal.JournalEntry", "JournalEntry")
                        .WithMany("ProductAssociations")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntryTagAssignment", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Journal.JournalEntry", "JournalEntry")
                        .WithMany("TagAssignments")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anela.Heblo.Domain.Features.Journal.JournalEntryTag", "Tag")
                        .WithMany("TagAssignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.GiftPackageManufacture.GiftPackageManufactureItem", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Logistics.GiftPackageManufacture.GiftPackageManufactureLog", "ManufactureLog")
                        .WithMany("ConsumedItems")
                        .HasForeignKey("ManufactureLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufactureLog");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBoxItem", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBox", null)
                        .WithMany("Items")
                        .HasForeignKey("TransportBoxId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBoxStateLog", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBox", null)
                        .WithMany("StateLog")
                        .HasForeignKey("TransportBoxId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrderNote", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrder", "ManufactureOrder")
                        .WithMany("Notes")
                        .HasForeignKey("ManufactureOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufactureOrder");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrderProduct", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrder", "ManufactureOrder")
                        .WithMany("Products")
                        .HasForeignKey("ManufactureOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManufactureOrder");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrderSemiProduct", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrder", "ManufactureOrder")
                        .WithOne("SemiProduct")
                        .HasForeignKey("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrderSemiProduct", "ManufactureOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ManufactureOrder");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.PackingMaterials.PackingMaterialLog", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.PackingMaterials.PackingMaterial", null)
                        .WithMany("Logs")
                        .HasForeignKey("PackingMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Purchase.PurchaseOrderHistory", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Purchase.PurchaseOrder", null)
                        .WithMany("History")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Purchase.PurchaseOrderLine", b =>
                {
                    b.HasOne("Anela.Heblo.Domain.Features.Purchase.PurchaseOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Anela.Heblo.Xcc.Domain.UserDashboardTile", b =>
                {
                    b.HasOne("Anela.Heblo.Xcc.Domain.UserDashboardSettings", "DashboardSettings")
                        .WithMany("Tiles")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DashboardSettings");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Invoices.IssuedInvoice", b =>
                {
                    b.Navigation("SyncHistory");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntry", b =>
                {
                    b.Navigation("ProductAssociations");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Journal.JournalEntryTag", b =>
                {
                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.GiftPackageManufacture.GiftPackageManufactureLog", b =>
                {
                    b.Navigation("ConsumedItems");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Logistics.Transport.TransportBox", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StateLog");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Manufacture.ManufactureOrder", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Products");

                    b.Navigation("SemiProduct");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.PackingMaterials.PackingMaterial", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Anela.Heblo.Domain.Features.Purchase.PurchaseOrder", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Anela.Heblo.Xcc.Domain.UserDashboardSettings", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
