from docs_model import ProcessDoc
from index_gen import render_index


def d(process, kind, summary, related=()):
    return ProcessDoc(f"docs/processes/{process}.md", process, kind, summary, ("x",), "abcdef1", related, "")


def test_index_groups_by_kind_in_fixed_order_and_sorts_names():
    text = render_index([
        d("feed-metabase", "feed", "Views for Metabase."),
        d("calc-margins", "calculation", "M0-M3 margins.", ("sync-flexi",)),
        d("sync-flexi", "sync", "Flexi ledger mirror."),
        d("calc-alpha", "calculation", "Alpha."),
    ])
    assert text.startswith("<!-- GENERATED by scripts/process-docs/check.py index")
    assert text.index("## Syncs") < text.index("## Calculations") < text.index("## Feeds")
    assert text.index("calc-alpha") < text.index("calc-margins")
    assert "- [calc-margins](calc-margins.md) — M0-M3 margins. Related: sync-flexi" in text


def test_empty_kind_section_is_omitted():
    assert "## Feeds" not in render_index([d("sync-a", "sync", "A.")])
