from docs_model import ProcessDoc
from index_gen import render_index


def d(process, kind, summary, related=(), module="catalog"):
    return ProcessDoc(f"docs/processes/{process}.md", process, kind, module, summary, ("x",), "abcdef1", related, "")


def test_index_groups_by_module_and_orders_processes_by_kind_then_name():
    text = render_index([
        d("module-catalog", "module", "Product master."),
        d("feed-stock-up", "feed", "Stock to Shoptet."),
        d("calc-margins", "calculation", "M0-M3 margins.", ("sync-flexi",)),
        d("sync-flexi", "sync", "Flexi ledger mirror.", module="analytics"),
        d("calc-alpha", "calculation", "Alpha."),
    ])
    assert text.startswith("<!-- GENERATED by scripts/process-docs/check.py index")
    assert text.index("## analytics") < text.index("## catalog")
    catalog = text[text.index("## catalog"):]
    assert "[module-catalog](module-catalog.md) — Product master." in catalog
    assert catalog.index("calc-alpha") < catalog.index("calc-margins") < catalog.index("feed-stock-up")
    assert "- [calc-margins](calc-margins.md) (calculation) — M0-M3 margins. Related: sync-flexi" in text


def test_module_without_overview_doc_is_marked():
    text = render_index([d("sync-a", "sync", "A.", module="bank")])
    assert "## bank\n\n_No module overview doc yet._" in text


def test_module_doc_is_not_listed_as_a_process():
    text = render_index([d("module-bank", "module", "Bank.", module="bank")])
    assert "- [module-bank]" not in text
