using Anela.Heblo.Domain.Features.Smartsupp;
using Anela.Heblo.Persistence;
using Anela.Heblo.Persistence.Smartsupp;
using Anela.Heblo.Tests.Common;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Xunit;

namespace Anela.Heblo.Tests.Persistence.Smartsupp;

[Collection("PostgresIntegration")]
[Trait("Category", "Integration")]
public class SmartsuppPresenceRepositoryIntegrationTests : IAsyncLifetime
{
    private readonly PostgresSharedContainerFixture _fixture;
    private string _connectionString = null!;
    private ApplicationDbContext _context = null!;

    public SmartsuppPresenceRepositoryIntegrationTests(PostgresSharedContainerFixture fixture)
    {
        _fixture = fixture;
    }

    public async Task InitializeAsync()
    {
        _connectionString = await _fixture.CreateDatabaseAsync("smartsupp_presence_x");

        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            CREATE SCHEMA IF NOT EXISTS public;

            CREATE TABLE IF NOT EXISTS public."SmartsuppConversationPresences" (
                "Id"             bigint                       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ConversationId" character varying(100)       NOT NULL,
                "AgentId"        character varying(200)       NOT NULL,
                "DisplayName"    character varying(200)       NOT NULL,
                "Source"         character varying(20)        NOT NULL,
                "EnteredAt"      timestamp without time zone  NOT NULL,
                "LastSeenAt"     timestamp without time zone  NOT NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SmartsuppConversationPresences_ConversationId_AgentId_Source"
                ON public."SmartsuppConversationPresences" ("ConversationId", "AgentId", "Source");
            """;
        await cmd.ExecuteNonQueryAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseNpgsql(_connectionString)
            .Options;
        _context = new ApplicationDbContext(options);
    }

    public async Task DisposeAsync() => await _context.DisposeAsync();

    private SmartsuppPresenceRepository CreateRepository() => new(_context);

    private static SmartsuppConversationPresence MakePresence(
        string conversationId,
        string agentId,
        SmartsuppPresenceSource source,
        DateTime enteredAt,
        DateTime lastSeenAt,
        string displayName = "Op") =>
        new()
        {
            ConversationId = conversationId,
            AgentId = agentId,
            DisplayName = displayName,
            Source = source,
            EnteredAt = DateTime.SpecifyKind(enteredAt, DateTimeKind.Unspecified),
            LastSeenAt = DateTime.SpecifyKind(lastSeenAt, DateTimeKind.Unspecified),
        };

    private async Task<(DateTime EnteredAt, DateTime LastSeenAt, string DisplayName)?> ReadRowAsync(
        string conversationId, string agentId, SmartsuppPresenceSource source)
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            SELECT "EnteredAt", "LastSeenAt", "DisplayName"
            FROM public."SmartsuppConversationPresences"
            WHERE "ConversationId" = @c AND "AgentId" = @a AND "Source" = @s
            """;
        cmd.Parameters.AddWithValue("c", conversationId);
        cmd.Parameters.AddWithValue("a", agentId);
        cmd.Parameters.AddWithValue("s", source.ToString());
        await using var reader = await cmd.ExecuteReaderAsync();
        if (!await reader.ReadAsync())
            return null;
        return (reader.GetDateTime(0), reader.GetDateTime(1), reader.GetString(2));
    }

    [Fact]
    public async Task UpsertAsync_InsertsRow_WithUnspecifiedTimestamps()
    {
        // Regression: Kind=Unspecified UTC values must persist to a 'timestamp without time zone' column.
        var repo = CreateRepository();
        var now = new DateTime(2026, 7, 9, 10, 0, 0);

        await repo.UpsertAsync(
            MakePresence("c1", "a1", SmartsuppPresenceSource.Heblo, now, now, "Ondra"),
            CancellationToken.None);

        var row = await ReadRowAsync("c1", "a1", SmartsuppPresenceSource.Heblo);
        row.Should().NotBeNull();
        row!.Value.DisplayName.Should().Be("Ondra");
        row.Value.LastSeenAt.Should().Be(now);
    }

    [Fact]
    public async Task UpsertAsync_OnConflict_RefreshesLastSeen_PreservesEnteredAt()
    {
        var repo = CreateRepository();
        var entered = new DateTime(2026, 7, 9, 10, 0, 0);
        var seenLater = new DateTime(2026, 7, 9, 10, 5, 0);

        await repo.UpsertAsync(MakePresence("c1", "a1", SmartsuppPresenceSource.Heblo, entered, entered), CancellationToken.None);
        await repo.UpsertAsync(MakePresence("c1", "a1", SmartsuppPresenceSource.Heblo, seenLater, seenLater, "Renamed"), CancellationToken.None);

        var row = await ReadRowAsync("c1", "a1", SmartsuppPresenceSource.Heblo);
        row!.Value.EnteredAt.Should().Be(entered, "EnteredAt is preserved across heartbeats");
        row.Value.LastSeenAt.Should().Be(seenLater, "LastSeenAt is refreshed");
        row.Value.DisplayName.Should().Be("Renamed");
    }

    [Fact]
    public async Task GetActiveByConversationAsync_FiltersBySourceSpecificTtl()
    {
        var repo = CreateRepository();
        var now = new DateTime(2026, 7, 9, 12, 0, 0, DateTimeKind.Unspecified);
        var hebloThreshold = now.AddSeconds(-90);
        var smartsuppThreshold = now.AddMinutes(-30);

        // Heblo row seen 2 min ago -> expired (past 90s threshold).
        await repo.UpsertAsync(MakePresence("c1", "stale", SmartsuppPresenceSource.Heblo, now.AddMinutes(-2), now.AddMinutes(-2)), CancellationToken.None);
        // Heblo row seen 30s ago -> active.
        await repo.UpsertAsync(MakePresence("c1", "fresh", SmartsuppPresenceSource.Heblo, now.AddSeconds(-30), now.AddSeconds(-30)), CancellationToken.None);
        // Smartsupp row seen 10 min ago -> still active under the 30 min TTL.
        await repo.UpsertAsync(MakePresence("c1", "native", SmartsuppPresenceSource.Smartsupp, now.AddMinutes(-10), now.AddMinutes(-10)), CancellationToken.None);

        var active = await repo.GetActiveByConversationAsync(new[] { "c1" }, hebloThreshold, smartsuppThreshold, CancellationToken.None);

        active["c1"].Select(p => p.AgentId).Should().BeEquivalentTo(new[] { "fresh", "native" });
    }

    [Fact]
    public async Task RemoveAsync_DeletesOnlyMatchingSource()
    {
        var repo = CreateRepository();
        var now = new DateTime(2026, 7, 9, 12, 0, 0);
        await repo.UpsertAsync(MakePresence("c1", "a1", SmartsuppPresenceSource.Smartsupp, now, now), CancellationToken.None);
        await repo.UpsertAsync(MakePresence("c1", "a1", SmartsuppPresenceSource.Heblo, now, now), CancellationToken.None);

        await repo.RemoveAsync("c1", "a1", SmartsuppPresenceSource.Smartsupp, CancellationToken.None);

        (await ReadRowAsync("c1", "a1", SmartsuppPresenceSource.Smartsupp)).Should().BeNull();
        (await ReadRowAsync("c1", "a1", SmartsuppPresenceSource.Heblo)).Should().NotBeNull();
    }

    [Fact]
    public async Task PurgeExpiredAsync_DeletesOnlyExpiredRows()
    {
        var repo = CreateRepository();
        var now = new DateTime(2026, 7, 9, 12, 0, 0, DateTimeKind.Unspecified);
        await repo.UpsertAsync(MakePresence("c1", "old", SmartsuppPresenceSource.Heblo, now.AddHours(-2), now.AddHours(-2)), CancellationToken.None);
        await repo.UpsertAsync(MakePresence("c1", "new", SmartsuppPresenceSource.Heblo, now, now), CancellationToken.None);

        var deleted = await repo.PurgeExpiredAsync(now.AddMinutes(-5), now.AddMinutes(-5), CancellationToken.None);

        deleted.Should().Be(1);
        (await ReadRowAsync("c1", "old", SmartsuppPresenceSource.Heblo)).Should().BeNull();
        (await ReadRowAsync("c1", "new", SmartsuppPresenceSource.Heblo)).Should().NotBeNull();
    }
}
