// <auto-generated />
using System;
using Anela.Heblo.Persistence.Ga4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anela.Heblo.Persistence.Ga4.Migrations
{
    [DbContext(typeof(Ga4DbContext))]
    partial class Ga4DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ga4_agg")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anela.Heblo.Persistence.Ga4.Entities.ConversionsDaily", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ChannelGroup")
                        .HasColumnType("text")
                        .HasColumnName("channel_group");

                    b.Property<decimal>("PurchaseRevenue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("purchase_revenue");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<long>("Transactions")
                        .HasColumnType("bigint")
                        .HasColumnName("transactions");

                    b.HasKey("Date", "ChannelGroup");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_conversions_daily_date");

                    b.ToTable("conversions_daily", "ga4_agg");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ga4.Entities.LandingPageDaily", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("LandingPage")
                        .HasColumnType("text")
                        .HasColumnName("landing_page");

                    b.Property<long>("EngagedSessions")
                        .HasColumnType("bigint")
                        .HasColumnName("engaged_sessions");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint")
                        .HasColumnName("sessions");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Date", "LandingPage");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_landing_page_daily_date");

                    b.ToTable("landing_page_daily", "ga4_agg");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ga4.Entities.PageDaily", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("PagePath")
                        .HasColumnType("text")
                        .HasColumnName("page_path");

                    b.Property<string>("PageTitle")
                        .HasColumnType("text")
                        .HasColumnName("page_title");

                    b.Property<long>("ScreenPageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("screen_page_views");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint")
                        .HasColumnName("sessions");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Date", "PagePath");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_page_daily_date");

                    b.ToTable("page_daily", "ga4_agg");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ga4.Entities.SyncState", b =>
                {
                    b.Property<string>("EntityName")
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LastRunFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_finished_at");

                    b.Property<int?>("LastRunRowsFetched")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_rows_fetched");

                    b.Property<int?>("LastRunRowsUpserted")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_rows_upserted");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_started_at");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_run_status");

                    b.Property<int?>("TopNPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("top_n_per_day");

                    b.Property<DateOnly?>("WatermarkDate")
                        .HasColumnType("date")
                        .HasColumnName("watermark_date");

                    b.HasKey("EntityName");

                    b.ToTable("sync_state", "ga4_agg");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ga4.Entities.TrafficDaily", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("ChannelGroup")
                        .HasColumnType("text")
                        .HasColumnName("channel_group");

                    b.Property<long>("EngagedSessions")
                        .HasColumnType("bigint")
                        .HasColumnName("engaged_sessions");

                    b.Property<long>("NewUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("new_users");

                    b.Property<long>("ScreenPageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("screen_page_views");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint")
                        .HasColumnName("sessions");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("total_users");

                    b.Property<long>("UserEngagementSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("user_engagement_seconds");

                    b.HasKey("Date", "ChannelGroup");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_traffic_daily_date");

                    b.ToTable("traffic_daily", "ga4_agg");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ga4.Entities.TrafficMonthly", b =>
                {
                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<long>("EngagedSessions")
                        .HasColumnType("bigint")
                        .HasColumnName("engaged_sessions");

                    b.Property<long>("NewUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("new_users");

                    b.Property<long>("ScreenPageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("screen_page_views");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint")
                        .HasColumnName("sessions");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("total_users");

                    b.Property<long>("UserEngagementSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("user_engagement_seconds");

                    b.HasKey("Month");

                    b.ToTable("traffic_monthly", "ga4_agg");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ga4.Entities.TrafficTotalDaily", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("EngagedSessions")
                        .HasColumnType("bigint")
                        .HasColumnName("engaged_sessions");

                    b.Property<long>("NewUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("new_users");

                    b.Property<long>("ScreenPageViews")
                        .HasColumnType("bigint")
                        .HasColumnName("screen_page_views");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint")
                        .HasColumnName("sessions");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint")
                        .HasColumnName("total_users");

                    b.Property<long>("UserEngagementSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("user_engagement_seconds");

                    b.HasKey("Date");

                    b.ToTable("traffic_total_daily", "ga4_agg");
                });
#pragma warning restore 612, 618
        }
    }
}
