"""Render docs/processes/INDEX.md from process doc frontmatter."""
from docs_model import MODULE_KIND, ProcessDoc

KIND_ORDER = ("sync", "calculation", "feed", "job", "workflow")
HEADER = (
    "<!-- GENERATED by scripts/process-docs/check.py index — do not edit by hand -->\n"
    "# Process Index\n\n"
    "Agent-facing catalog of what Heblo does, grouped by module. Each module has an overview doc "
    "(`module-<name>`); each process — sync, calculation, feed, job or workflow — has its own doc. "
    "Open the linked doc for the full detail.\n"
)


def _line(doc: ProcessDoc) -> str:
    related = f" Related: {', '.join(doc.related)}" if doc.related else ""
    return f"- [{doc.process}]({doc.process}.md) ({doc.kind}) — {doc.summary}{related}"


def _process_key(doc: ProcessDoc) -> tuple[int, str]:
    return KIND_ORDER.index(doc.kind), doc.process


def render_index(docs: list[ProcessDoc]) -> str:
    modules = {d.module: d for d in docs if d.kind == MODULE_KIND}
    processes = [d for d in docs if d.kind != MODULE_KIND]
    parts = [HEADER]
    for slug in sorted(set(modules) | {d.module for d in processes}):
        overview = modules.get(slug)
        intro = (f"[{overview.process}]({overview.process}.md) — {overview.summary}\n"
                 if overview else "_No module overview doc yet._\n")
        members = sorted((d for d in processes if d.module == slug), key=_process_key)
        lines = "".join(_line(d) + "\n" for d in members)
        parts.append(f"\n## {slug}\n\n{intro}" + (f"\n{lines}" if lines else ""))
    return "".join(parts)
