"""Render docs/processes/INDEX.md from process doc frontmatter."""
from docs_model import ProcessDoc

SECTIONS = (("sync", "Syncs"), ("calculation", "Calculations"), ("feed", "Feeds"))
HEADER = (
    "<!-- GENERATED by scripts/process-docs/check.py index — do not edit by hand -->\n"
    "# Process Index\n\n"
    "Agent-facing catalog of Heblo syncs, calculations and data feeds. "
    "Open the linked doc for the full process.\n"
)


def _line(doc: ProcessDoc) -> str:
    related = f" Related: {', '.join(doc.related)}" if doc.related else ""
    return f"- [{doc.process}]({doc.process}.md) — {doc.summary}{related}"


def render_index(docs: list[ProcessDoc]) -> str:
    parts = [HEADER]
    for kind, title in SECTIONS:
        members = sorted((d for d in docs if d.kind == kind), key=lambda d: d.process)
        if members:
            parts.append(f"\n## {title}\n\n" + "\n".join(_line(d) for d in members) + "\n")
    return "".join(parts)
