// <auto-generated />
using System;
using Anela.Heblo.Persistence.Ads;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anela.Heblo.Persistence.Ads.Migrations
{
    [DbContext(typeof(AdsDbContext))]
    partial class AdsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ads")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_managed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_accounts_platform_external_id");

                    b.ToTable("ad_accounts", "ads");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdChangeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Actor")
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_kind");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_type");

                    b.Property<string>("EntityExternalRef")
                        .HasColumnType("text")
                        .HasColumnName("entity_external_ref");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_event_id");

                    b.Property<string>("MatchedExecutionId")
                        .HasColumnType("text")
                        .HasColumnName("matched_execution_id");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_ad_change_events_entity_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_ad_change_events_occurred_at");

                    b.HasIndex("AccountId", "Source", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_change_events_account_source_external_event_id");

                    b.ToTable("ad_change_events", "ads");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdDailyFact", b =>
                {
                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("Clicks")
                        .HasColumnType("bigint")
                        .HasColumnName("clicks");

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("conversion_value");

                    b.Property<decimal>("Conversions")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("conversions");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint")
                        .HasColumnName("impressions");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("EntityId", "Date");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_ad_daily_facts_date");

                    b.ToTable("ad_daily_facts", "ads");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_ad_entities_parent_id");

                    b.HasIndex("AccountId", "Level", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_ad_entities_account_level_external_id");

                    b.ToTable("ad_entities", "ads");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdSearchTermDaily", b =>
                {
                    b.Property<long>("AdGroupEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("ad_group_entity_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("SearchTerm")
                        .HasColumnType("text")
                        .HasColumnName("search_term");

                    b.Property<string>("MatchType")
                        .HasColumnType("text")
                        .HasColumnName("match_type");

                    b.Property<long>("Clicks")
                        .HasColumnType("bigint")
                        .HasColumnName("clicks");

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("conversion_value");

                    b.Property<decimal>("Conversions")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("conversions");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint")
                        .HasColumnName("impressions");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("AdGroupEntityId", "Date", "SearchTerm", "MatchType");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_ad_search_term_daily_date");

                    b.ToTable("ad_search_term_daily", "ads");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdSyncState", b =>
                {
                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("AccountExternalId")
                        .HasColumnType("text")
                        .HasColumnName("account_external_id");

                    b.Property<string>("Stream")
                        .HasColumnType("text")
                        .HasColumnName("stream");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("Watermark")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watermark");

                    b.HasKey("Platform", "AccountExternalId", "Stream");

                    b.ToTable("sync_state", "ads");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdChangeEvent", b =>
                {
                    b.HasOne("Anela.Heblo.Persistence.Ads.Entities.AdAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Anela.Heblo.Persistence.Ads.Entities.AdEntity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdDailyFact", b =>
                {
                    b.HasOne("Anela.Heblo.Persistence.Ads.Entities.AdEntity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdEntity", b =>
                {
                    b.HasOne("Anela.Heblo.Persistence.Ads.Entities.AdAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Anela.Heblo.Persistence.Ads.Entities.AdEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Ads.Entities.AdSearchTermDaily", b =>
                {
                    b.HasOne("Anela.Heblo.Persistence.Ads.Entities.AdEntity", null)
                        .WithMany()
                        .HasForeignKey("AdGroupEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
