// <auto-generated />
using System;
using Anela.Heblo.Persistence.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anela.Heblo.Persistence.Analytics.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260526122936_InitialAnalyticsSchema")]
    partial class InitialAnalyticsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flexi_raw")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anela.Heblo.Persistence.Analytics.Entities.AccountingTemplate", b =>
                {
                    b.Property<long>("FlexiId")
                        .HasColumnType("bigint")
                        .HasColumnName("flexi_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("FlexiId");

                    b.ToTable("accounting_template", "flexi_raw");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Analytics.Entities.Contact", b =>
                {
                    b.Property<long>("FlexiId")
                        .HasColumnType("bigint")
                        .HasColumnName("flexi_id");

                    b.Property<string>("Cin")
                        .HasColumnType("text")
                        .HasColumnName("cin");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Vatin")
                        .HasColumnType("text")
                        .HasColumnName("vatin");

                    b.HasKey("FlexiId");

                    b.ToTable("contact", "flexi_raw");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Analytics.Entities.Department", b =>
                {
                    b.Property<long>("FlexiId")
                        .HasColumnType("bigint")
                        .HasColumnName("flexi_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("FlexiId");

                    b.ToTable("department", "flexi_raw");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Analytics.Entities.LedgerEntry", b =>
                {
                    b.Property<long>("FlexiId")
                        .HasColumnType("bigint")
                        .HasColumnName("flexi_id");

                    b.Property<string>("AccountCredit")
                        .HasColumnType("text")
                        .HasColumnName("account_credit");

                    b.Property<string>("AccountDebit")
                        .HasColumnType("text")
                        .HasColumnName("account_debit");

                    b.Property<string>("AccountingTemplate")
                        .HasColumnType("text")
                        .HasColumnName("accounting_template");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text")
                        .HasColumnName("cost_center");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Period")
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("FlexiId");

                    b.HasIndex("AccountCredit")
                        .HasDatabaseName("ix_ledger_entry_account_credit");

                    b.HasIndex("AccountDebit")
                        .HasDatabaseName("ix_ledger_entry_account_debit");

                    b.HasIndex("CostCenter")
                        .HasDatabaseName("ix_ledger_entry_cost_center");

                    b.HasIndex("EntryDate")
                        .HasDatabaseName("ix_ledger_entry_entry_date");

                    b.HasIndex("LastModified")
                        .HasDatabaseName("ix_ledger_entry_last_modified");

                    b.ToTable("ledger_entry", "flexi_raw");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.Analytics.Entities.SyncState", b =>
                {
                    b.Property<string>("EntityName")
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LastRunFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_finished_at");

                    b.Property<int?>("LastRunRowsFetched")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_rows_fetched");

                    b.Property<int?>("LastRunRowsUpserted")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_rows_upserted");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_started_at");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_run_status");

                    b.Property<DateTimeOffset?>("Watermark")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watermark");

                    b.HasKey("EntityName");

                    b.ToTable("sync_state", "flexi_raw");
                });
#pragma warning restore 612, 618
        }
    }
}
