namespace Anela.Heblo.Domain.Features.Rag;

/// <summary>
/// A single AI answer-generation interaction captured for building an evaluation dataset.
/// Shared across all RAG-backed features (see <see cref="Feature"/>): it records the user question,
/// the retrieved chunks + similarity scores, the fully-rendered enriched prompt, the generated answer,
/// the answer the user actually kept/sent, and human quality feedback.
/// </summary>
public class RagInteractionLog
{
    public Guid Id { get; set; }

    public RagFeature Feature { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public string? UserId { get; set; }

    /// <summary>
    /// The query that drove retrieval. KnowledgeBase: the user question. Smartsupp: the topic hint
    /// or the last visitor messages used as the retrieval query.
    /// </summary>
    public string Question { get; set; } = string.Empty;

    /// <summary>The query-expansion output actually embedded for vector search, when available.</summary>
    public string? ExpandedQuery { get; set; }

    public int TopK { get; set; }

    public int SourceCount { get; set; }

    /// <summary>Serialized <c>List&lt;RagRetrievedChunk&gt;</c> (jsonb) — full chunk content + scores.</summary>
    public string RetrievedChunksJson { get; set; } = "[]";

    /// <summary>The fully-rendered system prompt sent to the LLM.</summary>
    public string SystemPrompt { get; set; } = string.Empty;

    /// <summary>The answer generated by the LLM.</summary>
    public string Answer { get; set; } = string.Empty;

    // --- Smartsupp linkage / sent-answer signal (null for KnowledgeBase) ---

    public string? ConversationId { get; set; }

    public string? Topic { get; set; }

    /// <summary>The text the agent actually sent, set when a message linked to this draft is sent.</summary>
    public string? SentAnswer { get; set; }

    /// <summary>True when the sent text differs from the generated answer.</summary>
    public bool? WasEdited { get; set; }

    public DateTimeOffset? SentAt { get; set; }

    // --- Human feedback ---

    public int? PrecisionScore { get; set; }

    public int? StyleScore { get; set; }

    public string? FeedbackComment { get; set; }

    public long DurationMs { get; set; }
}
