using System.Text;
using System.Text.Json;
using Anela.Heblo.Domain.Features.Authorization;

var tsPath = args.ElementAtOrDefault(0) ?? "frontend/src/auth/accessMatrix.generated.ts";
var jsonPath = args.ElementAtOrDefault(1) ?? "access-matrix.generated.json";
var csPath = args.ElementAtOrDefault(2)
    ?? "backend/src/Anela.Heblo.Domain/Features/Authorization/AccessRoles.generated.cs";

var roles = AccessMatrix.Roles().ToList();

// 1. JSON manifest for the Entra provisioning script.
var featureRoles = roles.Select(r => new
{
    id = DeterministicGuid.ForRole(r.Value).ToString(),
    allowedMemberTypes = new[] { "User" },
    description = $"{r.Feature} {r.Level}",
    displayName = r.Value,
    isEnabled = true,
    value = r.Value
});
var superUserRole = new[]
{
    new
    {
        id = DeterministicGuid.ForRole("super_user").ToString(),
        allowedMemberTypes = new[] { "User" },
        description = "Break-glass: grants all permissions regardless of DB group assignments",
        displayName = "super_user",
        isEnabled = true,
        value = "super_user",
    }
};
var appRoles = superUserRole.Concat(featureRoles);
var groups = AccessMatrix.Groups.Select(g => new { name = g.Name, roles = g.Roles });
var manifest = new { appRoles, groups };
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(jsonPath)) ?? ".");
File.WriteAllText(jsonPath,
    JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }));

// 2. TS map for the frontend: ACCESS_ROUTES with MenuRequirement shape.
var ts = new StringBuilder();
ts.AppendLine("// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.");
ts.AppendLine("export interface MenuRequirement { permissions: string[]; }");
ts.AppendLine("export const ACCESS_ROUTES: Record<string, MenuRequirement> = {");
foreach (var menu in AccessMatrix.MenuPaths)
{
    var perms = string.Join(", ", menu.Requires.Select(r =>
        $"\"{PermissionString.Format(r.Feature, r.Level)}\""));
    ts.AppendLine($"  \"{menu.Key}\": {{ permissions: [{perms}] }},");
}
ts.AppendLine("};");
ts.AppendLine();
ts.AppendLine("export const ACCESS_ROLES = [");
foreach (var r in roles) ts.AppendLine($"  \"{r.Value}\",");
ts.AppendLine("] as const;");
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(tsPath)) ?? ".");
File.WriteAllText(tsPath, ts.ToString());

// 3. C# constants for [Authorize(Roles = AccessRoles.X)].
var cs = new StringBuilder();
cs.AppendLine("// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.");
cs.AppendLine("namespace Anela.Heblo.Domain.Features.Authorization;");
cs.AppendLine();
cs.AppendLine("public static class AccessRoles");
cs.AppendLine("{");
cs.AppendLine("    public const string Base = \"heblo_user\";");
cs.AppendLine("    public const string SuperUser = \"super_user\";");
cs.AppendLine();
foreach (var r in roles)
{
    if (!Enum.TryParse<Feature>(r.Feature, out var feature)) continue;
    var levelSuffix = r.Level switch
    {
        AccessLevel.Read => "Read",
        AccessLevel.Write => "Write",
        AccessLevel.Admin => "Admin",
        _ => throw new InvalidOperationException($"Unknown level {r.Level}")
    };
    cs.AppendLine($"    public const string {PermissionString.ConstantSuffix(feature)}{levelSuffix} = \"{r.Value}\";");
}
cs.AppendLine();
cs.AppendLine("    public static string For(Feature feature, AccessLevel level) => (feature, level) switch");
cs.AppendLine("    {");
foreach (var r in roles)
{
    if (!Enum.TryParse<Feature>(r.Feature, out var feature)) continue;
    var levelName = r.Level switch
    {
        AccessLevel.Read  => "Read",
        AccessLevel.Write => "Write",
        AccessLevel.Admin => "Admin",
        _ => throw new InvalidOperationException($"Unknown level {r.Level}")
    };
    var suffix = $"{PermissionString.ConstantSuffix(feature)}{levelName}";
    cs.AppendLine($"        (Feature.{r.Feature}, AccessLevel.{levelName}) => {suffix},");
}
cs.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(feature), $\"Feature.{feature} does not support AccessLevel.{level}\")");
cs.AppendLine("    };");
cs.AppendLine("}");
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(csPath)) ?? ".");
File.WriteAllText(csPath, cs.ToString());

Console.WriteLine($"Wrote {tsPath}, {jsonPath}, and {csPath}");
