using System.Text;
using System.Text.Json;
using Anela.Heblo.Domain.Features.Authorization;

var tsPath = args.ElementAtOrDefault(0) ?? "frontend/src/auth/accessMatrix.generated.ts";
var jsonPath = args.ElementAtOrDefault(1) ?? "access-matrix.generated.json";

var roles = AccessMatrix.Roles().ToList();

// 1. JSON manifest for the az script.
var featureRoles = roles.Select(r => new
{
    id = DeterministicGuid.ForRole(r.Value).ToString(),
    allowedMemberTypes = new[] { "User" },
    description = $"{r.Feature} {r.Level}",
    displayName = r.Value,
    isEnabled = true,
    value = r.Value
});
var superUserRole = new[]
{
    new
    {
        id = DeterministicGuid.ForRole(AccessRoles.SuperUser).ToString(),
        allowedMemberTypes = new[] { "User" },
        description = "Break-glass: grants all permissions regardless of DB group assignments",
        displayName = AccessRoles.SuperUser,
        isEnabled = true,
        value = AccessRoles.SuperUser,
    }
};
var appRoles = superUserRole.Concat(featureRoles);
var groups = AccessMatrix.Groups.Select(g => new { name = g.Name, roles = g.Roles });
var manifest = new { appRoles, groups };
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(jsonPath)) ?? ".");
File.WriteAllText(jsonPath,
    JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }));

// 2. TS map for the frontend.
var sb = new StringBuilder();
sb.AppendLine("// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.");
sb.AppendLine("export const ACCESS_ROUTES: Record<string, string> = {");
foreach (var f in AccessMatrix.Features.Where(f => f.Path is not null))
    sb.AppendLine($"  \"{f.Path}\": \"{f.Key}.read\",");
sb.AppendLine("};");
sb.AppendLine();
sb.AppendLine("export const ACCESS_ROLES = [");
foreach (var r in roles) sb.AppendLine($"  \"{r.Value}\",");
sb.AppendLine("] as const;");
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(tsPath)) ?? ".");
File.WriteAllText(tsPath, sb.ToString());

Console.WriteLine($"Wrote {tsPath} and {jsonPath}");
