using System.Text;
using System.Text.Json;
using Anela.Heblo.Domain.Features.Authorization;

// Args:
//   [0] = path to access-matrix.json     (default: ./access-matrix.json)
//   [1] = path to Feature.generated.cs
//   [2] = path to AccessMatrix.generated.cs
//   [3] = path to AccessRoles.generated.cs
//   [4] = path to accessMatrix.generated.ts
//   [5] = path to access-matrix-entra.generated.json
var manifestPath = args.ElementAtOrDefault(0) ?? "access-matrix.json";
var featureEnumPath = args.ElementAtOrDefault(1)
    ?? "backend/src/Anela.Heblo.Domain/Features/Authorization/Feature.generated.cs";
var matrixDataPath = args.ElementAtOrDefault(2)
    ?? "backend/src/Anela.Heblo.Domain/Features/Authorization/AccessMatrix.generated.cs";
var rolesPath = args.ElementAtOrDefault(3)
    ?? "backend/src/Anela.Heblo.Domain/Features/Authorization/AccessRoles.generated.cs";
var tsPath = args.ElementAtOrDefault(4)
    ?? "frontend/src/auth/accessMatrix.generated.ts";
var entraPath = args.ElementAtOrDefault(5) ?? "access-matrix-entra.generated.json";

if (!File.Exists(manifestPath))
{
    Console.Error.WriteLine($"access-matrix.json not found at '{manifestPath}'");
    return 1;
}

var json = File.ReadAllText(manifestPath);
var manifest = JsonSerializer.Deserialize<AccessMatrixManifest>(json, new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true,
}) ?? throw new InvalidOperationException("Failed to deserialize access-matrix.json");

// ---------- 1. Feature.generated.cs ----------
var enumSb = new StringBuilder();
enumSb.AppendLine("// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.");
enumSb.AppendLine("namespace Anela.Heblo.Domain.Features.Authorization;");
enumSb.AppendLine();
enumSb.AppendLine("/// <summary>Module-prefixed feature identifier. Each value generates one or more");
enumSb.AppendLine("/// permission strings (feature.read / .write / .admin) based on the feature");
enumSb.AppendLine("/// definition in <see cref=\"AccessMatrix\"/>.</summary>");
enumSb.AppendLine("public enum Feature");
enumSb.AppendLine("{");
foreach (var f in manifest.Features)
    enumSb.AppendLine($"    {f.Key},");
enumSb.AppendLine("}");
WriteFile(featureEnumPath, enumSb.ToString());

// ---------- 2. AccessMatrix.generated.cs ----------
var matrixSb = new StringBuilder();
matrixSb.AppendLine("// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.");
matrixSb.AppendLine("namespace Anela.Heblo.Domain.Features.Authorization;");
matrixSb.AppendLine();
matrixSb.AppendLine("public static class AccessMatrix");
matrixSb.AppendLine("{");
matrixSb.AppendLine($"    public const string BaseRole = \"{manifest.BaseRole}\";");
matrixSb.AppendLine();
matrixSb.AppendLine("    public static readonly IReadOnlyList<FeatureDefinition> Features = new[]");
matrixSb.AppendLine("    {");
foreach (var f in manifest.Features)
{
    var fArgs = new List<string> { $"Feature.{f.Key}", Escape(f.Label) };
    if (f.HasWrite) fArgs.Add("HasWrite: true");
    if (f.HasAdmin) fArgs.Add("HasAdmin: true");
    matrixSb.AppendLine($"        new FeatureDefinition({string.Join(", ", fArgs)}),");
}
matrixSb.AppendLine("    };");
matrixSb.AppendLine();
matrixSb.AppendLine("    public static readonly IReadOnlyList<MenuPath> MenuPaths = new[]");
matrixSb.AppendLine("    {");
foreach (var mp in manifest.MenuPaths)
{
    var reqs = string.Join(", ", mp.Requires.Select(r =>
        $"new FeaturePermission(Feature.{r.Feature}, AccessLevel.{r.Level})"));
    matrixSb.AppendLine($"        new MenuPath({Escape(mp.Path)}, new FeaturePermission[] {{ {reqs} }}),");
}
matrixSb.AppendLine("    };");
matrixSb.AppendLine();
matrixSb.AppendLine("    public static IEnumerable<AccessRoleDefinition> Roles()");
matrixSb.AppendLine("    {");
matrixSb.AppendLine("        foreach (var f in Features)");
matrixSb.AppendLine("        {");
matrixSb.AppendLine("            yield return new AccessRoleDefinition(");
matrixSb.AppendLine("                PermissionString.Format(f.Key, AccessLevel.Read), f.Key.ToString(), AccessLevel.Read);");
matrixSb.AppendLine("            if (f.HasWrite)");
matrixSb.AppendLine("                yield return new AccessRoleDefinition(");
matrixSb.AppendLine("                    PermissionString.Format(f.Key, AccessLevel.Write), f.Key.ToString(), AccessLevel.Write);");
matrixSb.AppendLine("            if (f.HasAdmin)");
matrixSb.AppendLine("                yield return new AccessRoleDefinition(");
matrixSb.AppendLine("                    PermissionString.Format(f.Key, AccessLevel.Admin), f.Key.ToString(), AccessLevel.Admin);");
matrixSb.AppendLine("        }");
matrixSb.AppendLine("    }");
matrixSb.AppendLine();
matrixSb.AppendLine("    public static IEnumerable<string> AllPermissionStrings() => Roles().Select(r => r.Value);");
matrixSb.AppendLine("    public static IEnumerable<string> AllRoleValues() => AllPermissionStrings();");
matrixSb.AppendLine("}");
WriteFile(matrixDataPath, matrixSb.ToString());

// ---------- 3. AccessRoles.generated.cs ----------
// We must compute role values here without depending on the (regenerated) AccessMatrix.
var roles = manifest.Features.SelectMany(f => RolesFor(f)).ToList();
var rolesSb = new StringBuilder();
rolesSb.AppendLine("// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.");
rolesSb.AppendLine("namespace Anela.Heblo.Domain.Features.Authorization;");
rolesSb.AppendLine();
rolesSb.AppendLine("public static class AccessRoles");
rolesSb.AppendLine("{");
rolesSb.AppendLine($"    public const string Base = \"{manifest.BaseRole}\";");
rolesSb.AppendLine("    public const string SuperUser = \"super_user\";");
rolesSb.AppendLine();
foreach (var (value, featureKey, level) in roles)
{
    var suffix = featureKey.Replace("_", "");
    var levelName = level;
    rolesSb.AppendLine($"    public const string {suffix}{levelName} = \"{value}\";");
}
rolesSb.AppendLine();
rolesSb.AppendLine("    public static string For(Feature feature, AccessLevel level) => (feature, level) switch");
rolesSb.AppendLine("    {");
foreach (var (value, featureKey, level) in roles)
{
    var suffix = featureKey.Replace("_", "");
    rolesSb.AppendLine($"        (Feature.{featureKey}, AccessLevel.{level}) => {suffix}{level},");
}
rolesSb.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(feature), $\"Feature.{feature} does not support AccessLevel.{level}\")");
rolesSb.AppendLine("    };");
rolesSb.AppendLine("}");
WriteFile(rolesPath, rolesSb.ToString());

// ---------- 4. accessMatrix.generated.ts ----------
var tsSb = new StringBuilder();
tsSb.AppendLine("// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.");
tsSb.AppendLine("export interface MenuRequirement { permissions: string[]; }");
tsSb.AppendLine("export const ACCESS_ROUTES: Record<string, MenuRequirement> = {");
foreach (var mp in manifest.MenuPaths)
{
    var perms = string.Join(", ", mp.Requires.Select(r =>
        $"\"{RoleStringFor(r.Feature, r.Level)}\""));
    tsSb.AppendLine($"  \"{mp.Path}\": {{ permissions: [{perms}] }},");
}
tsSb.AppendLine("};");
tsSb.AppendLine();
tsSb.AppendLine("export const ACCESS_ROLES = [");
foreach (var (value, _, _) in roles)
    tsSb.AppendLine($"  \"{value}\",");
tsSb.AppendLine("] as const;");
WriteFile(tsPath, tsSb.ToString());

// ---------- 5. access-matrix-entra.generated.json ----------
var featureRoles = roles.Select(r => new
{
    id = DeterministicGuid.ForRole(r.Value).ToString(),
    allowedMemberTypes = new[] { "User" },
    description = $"{r.FeatureKey} {r.Level}",
    displayName = r.Value,
    isEnabled = true,
    value = r.Value,
});
var superUserRole = new[]
{
    new
    {
        id = DeterministicGuid.ForRole("super_user").ToString(),
        allowedMemberTypes = new[] { "User" },
        description = "Break-glass: grants all permissions regardless of DB group assignments",
        displayName = "super_user",
        isEnabled = true,
        value = "super_user",
    },
};
var entraManifest = new
{
    appRoles = superUserRole.Concat(featureRoles),
    groups = manifest.SeedGroups.Select(g => new { name = g.Name, roles = g.Roles }),
};
WriteFile(entraPath, JsonSerializer.Serialize(entraManifest, new JsonSerializerOptions { WriteIndented = true }));

Console.WriteLine($"Wrote {featureEnumPath}, {matrixDataPath}, {rolesPath}, {tsPath}, {entraPath}");
return 0;

static void WriteFile(string path, string content)
{
    Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path)) ?? ".");
    File.WriteAllText(path, content);
}

static string Escape(string s) => $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

static string RoleStringFor(string featureKey, string levelName)
{
    var parts = featureKey.Split('_', 2);
    var module = ToSnake(parts[0]);
    var feature = ToSnake(parts[1]);
    var level = levelName.ToLowerInvariant();
    return $"{module}.{feature}.{level}";
}

static string ToSnake(string pascal)
{
    var sb = new StringBuilder();
    for (var i = 0; i < pascal.Length; i++)
    {
        if (i > 0 && char.IsUpper(pascal[i])) sb.Append('_');
        sb.Append(char.ToLowerInvariant(pascal[i]));
    }
    return sb.ToString();
}

static IEnumerable<(string Value, string FeatureKey, string Level)> RolesFor(FeatureEntry f)
{
    yield return (RoleStringFor(f.Key, "Read"), f.Key, "Read");
    if (f.HasWrite) yield return (RoleStringFor(f.Key, "Write"), f.Key, "Write");
    if (f.HasAdmin) yield return (RoleStringFor(f.Key, "Admin"), f.Key, "Admin");
}
