// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.
namespace Anela.Heblo.Domain.Features.Authorization;

public static class AccessRoles
{
    public const string Base = "heblo_user";
    public const string SuperUser = "super_user";

    public const string FinanceFinancialOverviewRead = "finance.financial_overview.read";
    public const string FinanceMarginAnalysisRead = "finance.margin_analysis.read";
    public const string ProductsProductMarginsRead = "products.product_margins.read";
    public const string ProductsCatalogRead = "products.catalog.read";
    public const string ProductsCatalogWrite = "products.catalog.write";
    public const string ProductsJournalRead = "products.journal.read";
    public const string ProductsJournalWrite = "products.journal.write";
    public const string CustomerBankStatementsRead = "customer.bank_statements.read";
    public const string CustomerKnowledgeBaseRead = "customer.knowledge_base.read";
    public const string CustomerKnowledgeBaseWrite = "customer.knowledge_base.write";
    public const string CustomerSmartsuppRead = "customer.smartsupp.read";
    public const string PurchasePurchaseOrdersRead = "purchase.purchase_orders.read";
    public const string PurchasePurchaseOrdersWrite = "purchase.purchase_orders.write";
    public const string PurchasePurchaseStockRead = "purchase.purchase_stock.read";
    public const string ManufactureManufactureOrdersRead = "manufacture.manufacture_orders.read";
    public const string ManufactureManufactureOrdersWrite = "manufacture.manufacture_orders.write";
    public const string ManufactureBatchPlanningRead = "manufacture.batch_planning.read";
    public const string ManufactureBatchPlanningWrite = "manufacture.batch_planning.write";
    public const string ManufactureManufactureOutputRead = "manufacture.manufacture_output.read";
    public const string ManufactureManufactureStockRead = "manufacture.manufacture_stock.read";
    public const string ManufactureMaterialInventoryRead = "manufacture.material_inventory.read";
    public const string ManufactureMaterialInventoryWrite = "manufacture.material_inventory.write";
    public const string ManufactureProductInventoryRead = "manufacture.product_inventory.read";
    public const string ManufactureProductInventoryWrite = "manufacture.product_inventory.write";
    public const string ManufactureMaterialContainersRead = "manufacture.material_containers.read";
    public const string ManufactureMaterialContainersWrite = "manufacture.material_containers.write";
    public const string WarehouseLogisticsRead = "warehouse.logistics.read";
    public const string WarehouseLogisticsWrite = "warehouse.logistics.write";
    public const string WarehouseExpeditionRead = "warehouse.expedition.read";
    public const string WarehouseExpeditionWrite = "warehouse.expedition.write";
    public const string WarehousePackagingRead = "warehouse.packaging.read";
    public const string WarehousePackagingWrite = "warehouse.packaging.write";
    public const string WarehouseStockUpRead = "warehouse.stock_up.read";
    public const string WarehouseStockUpWrite = "warehouse.stock_up.write";
    public const string MarketingArticleRead = "marketing.article.read";
    public const string MarketingArticleWrite = "marketing.article.write";
    public const string MarketingLeafletRead = "marketing.leaflet.read";
    public const string MarketingLeafletWrite = "marketing.leaflet.write";
    public const string MarketingPhotobankRead = "marketing.photobank.read";
    public const string MarketingPhotobankWrite = "marketing.photobank.write";
    public const string MarketingPhotobankAdmin = "marketing.photobank.admin";
    public const string MarketingMarketingCalendarRead = "marketing.marketing_calendar.read";
    public const string MarketingMarketingCalendarWrite = "marketing.marketing_calendar.write";
    public const string AnelaMeetingsRead = "anela.meetings.read";
    public const string AnelaMeetingsWrite = "anela.meetings.write";
    public const string AnelaOrgChartRead = "anela.org_chart.read";
    public const string AdminDataQualityRead = "admin.data_quality.read";
    public const string AdminDataQualityWrite = "admin.data_quality.write";
    public const string AdminAdministrationRead = "admin.administration.read";
    public const string AdminAdministrationWrite = "admin.administration.write";
    public const string AdminFeatureFlagsRead = "admin.feature_flags.read";
    public const string AdminFeatureFlagsWrite = "admin.feature_flags.write";
}
