// AUTO-GENERATED by Anela.Heblo.AccessMatrixGen. Do not edit by hand.
namespace Anela.Heblo.Domain.Features.Authorization;

public static class AccessMatrix
{
    public const string BaseRole = "heblo_user";

    public static readonly IReadOnlyList<FeatureDefinition> Features = new[]
    {
        new FeatureDefinition(Feature.Finance_FinancialOverview, "Finanční přehled"),
        new FeatureDefinition(Feature.Finance_MarginAnalysis, "Analýza marží"),
        new FeatureDefinition(Feature.Products_ProductMargins, "Marže produktů"),
        new FeatureDefinition(Feature.Products_Catalog, "Katalog", HasWrite: true),
        new FeatureDefinition(Feature.Products_Journal, "Žurnál", HasWrite: true),
        new FeatureDefinition(Feature.Customer_BankStatements, "Bankovní výpisy"),
        new FeatureDefinition(Feature.Customer_KnowledgeBase, "Znalostní báze", HasWrite: true),
        new FeatureDefinition(Feature.Customer_Smartsupp, "Smartsupp"),
        new FeatureDefinition(Feature.Purchase_PurchaseOrders, "Nákupní objednávky", HasWrite: true),
        new FeatureDefinition(Feature.Purchase_InvoiceClassification, "Klasifikace faktur", HasWrite: true),
        new FeatureDefinition(Feature.Purchase_PurchaseStock, "Analýza skladu (nákup)"),
        new FeatureDefinition(Feature.Manufacture_ManufactureOrders, "Výrobní objednávky", HasWrite: true),
        new FeatureDefinition(Feature.Manufacture_BatchPlanning, "Plánování šarží", HasWrite: true),
        new FeatureDefinition(Feature.Manufacture_ManufactureOutput, "Výstup výroby"),
        new FeatureDefinition(Feature.Manufacture_ManufactureStock, "Analýza skladu (výroba)"),
        new FeatureDefinition(Feature.Manufacture_MaterialInventory, "Inventura materiálu", HasWrite: true),
        new FeatureDefinition(Feature.Manufacture_ProductInventory, "Inventura produktů", HasWrite: true),
        new FeatureDefinition(Feature.Manufacture_MaterialContainers, "Kontejnery materiálu", HasWrite: true),
        new FeatureDefinition(Feature.Warehouse_Logistics, "Logistika", HasWrite: true),
        new FeatureDefinition(Feature.Warehouse_Expedition, "Expedice", HasWrite: true),
        new FeatureDefinition(Feature.Warehouse_Packaging, "Balení", HasWrite: true),
        new FeatureDefinition(Feature.Warehouse_StockUp, "Naskladnění", HasWrite: true),
        new FeatureDefinition(Feature.Marketing_Article, "Články", HasWrite: true),
        new FeatureDefinition(Feature.Marketing_Leaflet, "Generátor letáků", HasWrite: true),
        new FeatureDefinition(Feature.Marketing_Photobank, "Fotobanka", HasWrite: true, HasAdmin: true),
        new FeatureDefinition(Feature.Marketing_MarketingCalendar, "Marketingový kalendář", HasWrite: true),
        new FeatureDefinition(Feature.Anela_Meetings, "Schůzky", HasWrite: true),
        new FeatureDefinition(Feature.Anela_OrgChart, "Organigram"),
        new FeatureDefinition(Feature.Admin_DataQuality, "Kvalita dat", HasWrite: true),
        new FeatureDefinition(Feature.Admin_Administration, "Administrace", HasWrite: true),
        new FeatureDefinition(Feature.Admin_FeatureFlags, "Feature příznaky", HasWrite: true),
        new FeatureDefinition(Feature.Jobs_Trigger, "Spouštění úloh"),
        new FeatureDefinition(Feature.Jobs_Disable, "Vypínání úloh"),
    };

    public static readonly IReadOnlyList<MenuPath> MenuPaths = new[]
    {
        new MenuPath("/finance/overview", new FeaturePermission[] { new FeaturePermission(Feature.Finance_FinancialOverview, AccessLevel.Read) }),
        new MenuPath("/analytics/product-margin-summary", new FeaturePermission[] { new FeaturePermission(Feature.Finance_MarginAnalysis, AccessLevel.Read) }),
        new MenuPath("/products/margins", new FeaturePermission[] { new FeaturePermission(Feature.Products_ProductMargins, AccessLevel.Read) }),
        new MenuPath("/catalog", new FeaturePermission[] { new FeaturePermission(Feature.Products_Catalog, AccessLevel.Read) }),
        new MenuPath("/journal", new FeaturePermission[] { new FeaturePermission(Feature.Products_Journal, AccessLevel.Read) }),
        new MenuPath("/customer/issued-invoices", new FeaturePermission[] { new FeaturePermission(Feature.Customer_BankStatements, AccessLevel.Read) }),
        new MenuPath("/customer/bank-statements-overview", new FeaturePermission[] { new FeaturePermission(Feature.Customer_BankStatements, AccessLevel.Read) }),
        new MenuPath("/knowledge-base", new FeaturePermission[] { new FeaturePermission(Feature.Customer_KnowledgeBase, AccessLevel.Read) }),
        new MenuPath("/customer/smartsupp", new FeaturePermission[] { new FeaturePermission(Feature.Customer_Smartsupp, AccessLevel.Read) }),
        new MenuPath("/purchase/orders", new FeaturePermission[] { new FeaturePermission(Feature.Purchase_PurchaseOrders, AccessLevel.Read) }),
        new MenuPath("/purchase/invoice-classification", new FeaturePermission[] { new FeaturePermission(Feature.Purchase_InvoiceClassification, AccessLevel.Read) }),
        new MenuPath("/purchase/stock-analysis", new FeaturePermission[] { new FeaturePermission(Feature.Purchase_PurchaseStock, AccessLevel.Read) }),
        new MenuPath("/manufacturing/orders", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_ManufactureOrders, AccessLevel.Read) }),
        new MenuPath("/manufacturing/batch-planning", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_BatchPlanning, AccessLevel.Read) }),
        new MenuPath("/manufacturing/batch-calculator", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_BatchPlanning, AccessLevel.Read) }),
        new MenuPath("/manufacturing/output", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_ManufactureOutput, AccessLevel.Read) }),
        new MenuPath("/manufacturing/stock-analysis", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_ManufactureStock, AccessLevel.Read) }),
        new MenuPath("/manufacturing/inventory", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_MaterialInventory, AccessLevel.Read) }),
        new MenuPath("/manufacturing/product-inventory", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_ProductInventory, AccessLevel.Read) }),
        new MenuPath("/manufacturing/material-containers", new FeaturePermission[] { new FeaturePermission(Feature.Manufacture_MaterialContainers, AccessLevel.Read) }),
        new MenuPath("/logistics/inventory", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Logistics, AccessLevel.Read) }),
        new MenuPath("/logistics/receive-boxes", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Logistics, AccessLevel.Read) }),
        new MenuPath("/logistics/transport-boxes", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Logistics, AccessLevel.Read) }),
        new MenuPath("/logistics/packing-materials", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Logistics, AccessLevel.Read) }),
        new MenuPath("/logistics/expedition-archive", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Expedition, AccessLevel.Read) }),
        new MenuPath("/customer/expedition-settings", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Expedition, AccessLevel.Read) }),
        new MenuPath("/baleni", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Packaging, AccessLevel.Read) }),
        new MenuPath("/logistics/gift-package-manufacturing", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Packaging, AccessLevel.Read) }),
        new MenuPath("/stock-up-operations", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_StockUp, AccessLevel.Read) }),
        new MenuPath("/articles", new FeaturePermission[] { new FeaturePermission(Feature.Marketing_Article, AccessLevel.Read) }),
        new MenuPath("/marketing/feedback", new FeaturePermission[] { new FeaturePermission(Feature.Marketing_Article, AccessLevel.Write) }),
        new MenuPath("/leaflet-generator", new FeaturePermission[] { new FeaturePermission(Feature.Marketing_Leaflet, AccessLevel.Read) }),
        new MenuPath("/marketing/photobank", new FeaturePermission[] { new FeaturePermission(Feature.Marketing_Photobank, AccessLevel.Read) }),
        new MenuPath("/marketing/calendar", new FeaturePermission[] { new FeaturePermission(Feature.Marketing_MarketingCalendar, AccessLevel.Read) }),
        new MenuPath("/automation/meeting-tasks", new FeaturePermission[] { new FeaturePermission(Feature.Anela_Meetings, AccessLevel.Read) }),
        new MenuPath("#org-chart", new FeaturePermission[] { new FeaturePermission(Feature.Anela_OrgChart, AccessLevel.Read) }),
        new MenuPath("/automation/data-quality", new FeaturePermission[] { new FeaturePermission(Feature.Admin_DataQuality, AccessLevel.Read) }),
        new MenuPath("/admin/access", new FeaturePermission[] { new FeaturePermission(Feature.Admin_Administration, AccessLevel.Read) }),
        new MenuPath("/admin/access/groups/:id", new FeaturePermission[] { new FeaturePermission(Feature.Admin_Administration, AccessLevel.Read) }),
        new MenuPath("/admin/access/users/:id", new FeaturePermission[] { new FeaturePermission(Feature.Admin_Administration, AccessLevel.Read) }),
        new MenuPath("/automation/background-tasks", new FeaturePermission[] { new FeaturePermission(Feature.Admin_Administration, AccessLevel.Read) }),
        new MenuPath("/recurring-jobs", new FeaturePermission[] { new FeaturePermission(Feature.Admin_Administration, AccessLevel.Read) }),
        new MenuPath("#hangfire", new FeaturePermission[] { new FeaturePermission(Feature.Admin_Administration, AccessLevel.Read) }),
        new MenuPath("/admin/feature-flags", new FeaturePermission[] { new FeaturePermission(Feature.Admin_FeatureFlags, AccessLevel.Read) }),
        new MenuPath("#terminal", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Logistics, AccessLevel.Read) }),
        new MenuPath("#baleni-external", new FeaturePermission[] { new FeaturePermission(Feature.Warehouse_Packaging, AccessLevel.Read) }),
    };

    public static IEnumerable<AccessRoleDefinition> Roles()
    {
        foreach (var f in Features)
        {
            yield return new AccessRoleDefinition(
                PermissionString.Format(f.Key, AccessLevel.Read), f.Key.ToString(), AccessLevel.Read);
            if (f.HasWrite)
                yield return new AccessRoleDefinition(
                    PermissionString.Format(f.Key, AccessLevel.Write), f.Key.ToString(), AccessLevel.Write);
            if (f.HasAdmin)
                yield return new AccessRoleDefinition(
                    PermissionString.Format(f.Key, AccessLevel.Admin), f.Key.ToString(), AccessLevel.Admin);
        }
    }

    public static IEnumerable<string> AllPermissionStrings() => Roles().Select(r => r.Value);
    public static IEnumerable<string> AllRoleValues() => AllPermissionStrings();
}
