using Anela.Heblo.Domain.Features.MarketingPerformance;
using Anela.Heblo.Persistence;
using Anela.Heblo.Persistence.Marketing;
using Anela.Heblo.Tests.Common;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Xunit;

namespace Anela.Heblo.Tests.Features.MarketingPerformance;

/// <summary>
/// Real-Postgres cover for the refresh write path. The unit tests run on EF InMemory, which has no
/// timestamp/timestamptz distinction, so they cannot catch a column-type conflict between
/// <see cref="MarketingPerformanceMonthConfiguration"/> and the global DateTime value converter in
/// <see cref="ApplicationDbContext"/> (which rewrites every DateTime to Kind=Unspecified on write).
/// </summary>
[Collection("PostgresIntegration")]
[Trait("Category", "Integration")]
public class MarketingPerformanceMonthPersistenceIntegrationTests : IAsyncLifetime
{
    private readonly PostgresSharedContainerFixture _fixture;
    private string _connectionString = null!;
    private ApplicationDbContext _context = null!;
    private MarketingPerformanceRepository _repository = null!;

    public MarketingPerformanceMonthPersistenceIntegrationTests(PostgresSharedContainerFixture fixture)
    {
        _fixture = fixture;
    }

    public async Task InitializeAsync()
    {
        _connectionString = await _fixture.CreateDatabaseAsync("marketingperf");

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseNpgsql(_connectionString)
            .Options;

        _context = new ApplicationDbContext(options);

        // Create only the two marketing performance tables by hand. EnsureCreatedAsync would try to
        // install the "vector" extension, which the plain postgres:16 image does not ship.
        // Column types mirror the AddMarketingPerformance migration.
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            CREATE SCHEMA IF NOT EXISTS public;
            CREATE TABLE IF NOT EXISTS public."MarketingPerformanceMonths" (
                "Id"                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Year"                    integer                     NOT NULL,
                "Month"                   integer                     NOT NULL,
                "RetailOrderCount"        integer                     NOT NULL,
                "RetailRevenueWithVat"    numeric(18,2)               NOT NULL,
                "WholesaleOrderCount"     integer                     NOT NULL,
                "WholesaleRevenueWithVat" numeric(18,2)               NOT NULL,
                "SkippedEurInvoiceCount"  integer                     NOT NULL,
                "IsLocked"                boolean                     NOT NULL DEFAULT false,
                "RevenueComputedAt"       timestamp without time zone NULL,
                "CostsComputedAt"         timestamp without time zone NULL,
                "LastError"               text                        NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_MarketingPerformanceMonths_Year_Month"
                ON public."MarketingPerformanceMonths" ("Year", "Month");

            CREATE TABLE IF NOT EXISTS public."MarketingPerformanceChannelCosts" (
                "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MonthId"        integer                NOT NULL
                    REFERENCES public."MarketingPerformanceMonths" ("Id") ON DELETE CASCADE,
                "ChannelCode"    character varying(32)  NOT NULL,
                "CostWithoutVat" numeric(18,2)          NOT NULL,
                "InvoiceCount"   integer                NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_MarketingPerformanceChannelCosts_MonthId_ChannelCode"
                ON public."MarketingPerformanceChannelCosts" ("MonthId", "ChannelCode");
            """;
        await cmd.ExecuteNonQueryAsync();

        _repository = new MarketingPerformanceRepository(_context);
    }

    public async Task DisposeAsync() => await _context.DisposeAsync();

    [Fact]
    public async Task Persists_a_month_whose_computed_timestamps_were_assigned_as_utc()
    {
        // Arrange — exactly what MarketingPerformanceRefreshService.RefreshMonthAsync builds:
        // both stamps come from TimeProvider.GetUtcNow().UtcDateTime, i.e. Kind=Utc.
        var computedAt = DateTime.SpecifyKind(new DateTime(2026, 9, 22, 8, 5, 0), DateTimeKind.Utc);
        var month = new MarketingPerformanceMonth
        {
            Year = 2026,
            Month = 9,
            RetailOrderCount = 12,
            RetailRevenueWithVat = 3456.78m,
            RevenueComputedAt = computedAt,
            CostsComputedAt = computedAt,
        };
        month.ChannelCosts.Add(new MarketingPerformanceChannelCost
        {
            ChannelCode = "meta",
            CostWithoutVat = 1234.56m,
            InvoiceCount = 2,
        });

        // Act
        await _repository.AddAsync(month, CancellationToken.None);
        await _repository.SaveChangesAsync(CancellationToken.None);

        // Assert
        var stored = await _repository.GetRangeAsync(
            new YearMonth(2026, 9), new YearMonth(2026, 9), CancellationToken.None);

        stored.Should().ContainSingle();
        stored[0].RevenueComputedAt.Should().Be(computedAt);
        stored[0].CostsComputedAt.Should().Be(computedAt);
        stored[0].RetailRevenueWithVat.Should().Be(3456.78m);
        stored[0].ChannelCosts.Should().ContainSingle()
            .Which.CostWithoutVat.Should().Be(1234.56m);
    }
}
