// <auto-generated />
using System;
using Anela.Heblo.Persistence.ShoptetOrders;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anela.Heblo.Persistence.ShoptetOrders.Migrations
{
    [DbContext(typeof(ShoptetOrdersDbContext))]
    [Migration("20260922131918_InitialShoptetRawSchema")]
    partial class InitialShoptetRawSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shoptet_raw")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anela.Heblo.Persistence.ShoptetOrders.Entities.ShoptetOrder", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("BillingCity")
                        .HasColumnType("text")
                        .HasColumnName("billing_city");

                    b.Property<string>("BillingCompany")
                        .HasColumnType("text")
                        .HasColumnName("billing_company");

                    b.Property<string>("BillingCompanyId")
                        .HasColumnType("text")
                        .HasColumnName("billing_company_id");

                    b.Property<string>("BillingCountryCode")
                        .HasColumnType("text")
                        .HasColumnName("billing_country_code");

                    b.Property<int?>("BillingMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("billing_method_id");

                    b.Property<string>("BillingMethodName")
                        .HasColumnType("text")
                        .HasColumnName("billing_method_name");

                    b.Property<decimal>("BillingPriceWithVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("billing_price_with_vat");

                    b.Property<decimal>("BillingPriceWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("billing_price_without_vat");

                    b.Property<string>("BillingZip")
                        .HasColumnType("text")
                        .HasColumnName("billing_zip");

                    b.Property<bool>("CashDeskOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("cash_desk_order");

                    b.Property<DateTimeOffset?>("ChangeTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("change_time");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerGuid")
                        .HasColumnType("text")
                        .HasColumnName("customer_guid");

                    b.Property<decimal>("DiscountWithVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_with_vat");

                    b.Property<decimal>("DiscountWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_without_vat");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("text")
                        .HasColumnName("external_code");

                    b.Property<string>("Guid")
                        .HasColumnType("text")
                        .HasColumnName("guid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("PaymentMethodGuid")
                        .HasColumnType("text")
                        .HasColumnName("payment_method_guid");

                    b.Property<string>("PaymentMethodName")
                        .HasColumnType("text")
                        .HasColumnName("payment_method_name");

                    b.Property<decimal?>("PriceToPay")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_to_pay");

                    b.Property<decimal?>("PriceVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_vat");

                    b.Property<decimal?>("PriceWithVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_with_vat");

                    b.Property<decimal?>("PriceWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_without_vat");

                    b.Property<decimal>("ProductPriceWithVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("product_price_with_vat");

                    b.Property<decimal>("ProductPriceWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("product_price_without_vat");

                    b.Property<decimal>("ProductUnits")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("product_units");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Referer")
                        .HasColumnType("text")
                        .HasColumnName("referer");

                    b.Property<string>("SalesChannelGuid")
                        .HasColumnType("text")
                        .HasColumnName("sales_channel_guid");

                    b.Property<string>("ShippingGuid")
                        .HasColumnType("text")
                        .HasColumnName("shipping_guid");

                    b.Property<string>("ShippingName")
                        .HasColumnType("text")
                        .HasColumnName("shipping_name");

                    b.Property<decimal>("ShippingPriceWithVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shipping_price_with_vat");

                    b.Property<decimal>("ShippingPriceWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shipping_price_without_vat");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceName")
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .HasColumnType("text")
                        .HasColumnName("status_name");

                    b.Property<int?>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("VatMode")
                        .HasColumnType("text")
                        .HasColumnName("vat_mode");

                    b.Property<bool>("VatPayer")
                        .HasColumnType("boolean")
                        .HasColumnName("vat_payer");

                    b.HasKey("Code");

                    b.HasIndex("ChangeTime")
                        .HasDatabaseName("ix_order_change_time");

                    b.HasIndex("CustomerEmail")
                        .HasDatabaseName("ix_order_customer_email");

                    b.HasIndex("CustomerGuid")
                        .HasDatabaseName("ix_order_customer_guid");

                    b.HasIndex("OrderDate")
                        .HasDatabaseName("ix_order_order_date");

                    b.HasIndex("ShippingGuid")
                        .HasDatabaseName("ix_order_shipping_guid");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_order_status_id");

                    b.ToTable("order", "shoptet_raw");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.ShoptetOrders.Entities.ShoptetOrderItem", b =>
                {
                    b.Property<string>("OrderCode")
                        .HasColumnType("text")
                        .HasColumnName("order_code");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("amount");

                    b.Property<string>("AmountUnit")
                        .HasColumnType("text")
                        .HasColumnName("amount_unit");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<decimal?>("LinePriceVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_price_vat");

                    b.Property<decimal?>("LinePriceWithVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_price_with_vat");

                    b.Property<decimal?>("LinePriceWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_price_without_vat");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_item_id");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductGuid")
                        .HasColumnType("text")
                        .HasColumnName("product_guid");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductType")
                        .HasColumnType("text")
                        .HasColumnName("product_type");

                    b.Property<decimal?>("PurchasePriceWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("purchase_price_without_vat");

                    b.Property<string>("SourceArray")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_array");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<decimal?>("UnitPriceWithVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price_with_vat");

                    b.Property<decimal?>("UnitPriceWithoutVat")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price_without_vat");

                    b.Property<string>("VariantName")
                        .HasColumnType("text")
                        .HasColumnName("variant_name");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("vat_rate");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("weight");

                    b.HasKey("OrderCode", "LineNo");

                    b.HasIndex("ItemType")
                        .HasDatabaseName("ix_order_item_item_type");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("ix_order_item_product_code");

                    b.ToTable("order_item", "shoptet_raw");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.ShoptetOrders.Entities.ShoptetSyncState", b =>
                {
                    b.Property<string>("EntityName")
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<bool>("BackfillCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("backfill_completed");

                    b.Property<DateOnly?>("BackfillCursor")
                        .HasColumnType("date")
                        .HasColumnName("backfill_cursor");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LastRunFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_finished_at");

                    b.Property<int?>("LastRunRowsFetched")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_rows_fetched");

                    b.Property<int?>("LastRunRowsUpserted")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_rows_upserted");

                    b.Property<DateTimeOffset?>("LastRunStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_started_at");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_run_status");

                    b.Property<DateTimeOffset?>("Watermark")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watermark");

                    b.HasKey("EntityName");

                    b.ToTable("sync_state", "shoptet_raw");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.ShoptetOrders.Entities.ShoptetOrderItem", b =>
                {
                    b.HasOne("Anela.Heblo.Persistence.ShoptetOrders.Entities.ShoptetOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Anela.Heblo.Persistence.ShoptetOrders.Entities.ShoptetOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
